# Generated by Django 4.2 on 2023-04-30 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='crreated_at',
            new_name='created_at',
        ),
    ]
